# Generated by Django 4.2.2 on 2024-03-17 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work_related', 'Work Related'), ('culture_related', 'Culture Related')], max_length=20)),
                ('topic', models.CharField(choices=[('improvement_in_product', 'Improvement in Product Application'), ('team_collaboration_issues', 'Team Collaboration Issues'), ('growth_opportunities', 'Growth Opportunities for Employees'), ('hygiene', 'Hygiene at the Workplace'), ('infrastructure', 'Infrastructure Related'), ('sexual_harassment', 'Sexual Harassment')], max_length=30)),
                ('description', models.TextField()),
                ('effect', models.TextField()),
                ('suggestion', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
