# Generated by Django 4.2.2 on 2024-03-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='feedback',
            name='affected_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='department',
            field=models.CharField(choices=[('it', 'IT'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('office supplies', 'Office Supplies'), ('sales', 'Sales'), ('other', 'Other')], default='IT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('work_related', 'Work Related'), ('culture_related', 'Culture Related')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='users.user'),
        ),
    ]
