# Generated by Django 4.2.2 on 2024-03-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_suggestion_feedback_affected_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
