# Generated by Django 4.2.2 on 2024-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summarised_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('ai_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_problem', models.TextField(blank=True, null=True)),
                ('ai_solution', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
